version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache_server
    volumes:
      - ./public:/var/www/html
    environment:
      - DB_HOST=db
    ports:
      - "81:80"
    depends_on:
      - db
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: student
      PMA_PASSWORD: "@Student123"
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "@Root123"
      MYSQL_DATABASE: "students"
      MYSQL_USER: "student"
      MYSQL_PASSWORD: "@Student123"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
    driver: bridge
